stackname: kathautsavdashboardmodule
env_folder: env_vars
replicas:
  dev: 1
  prod: 5
restart_policy: any
max_mem: 1024M
max_cpu: 1
traefik_application_port: 7001
traefik_https_enable: true
traefik_ssl_provider: letsencrypt
vault:
  enabled: true
  name: katha-utsav-dashboard
  envs:
    - NODE_ENV
    - PG_DATABASE_HOST
    - PG_DATABASE_PORT
    - PG_DATABASE_NAME
    - PG_DATABASE_USERNAME
    - PG_DATABASE_PASSWORD
    - PG_DATABASE_SCHEMA
    - S3_BUCKET_NAME
    - S3_BUCKET_REGION
    - S3_FOLDER
    - JWT_SECRET_KEY
    - JWT_VALIDITY